# Generated by Django 5.1.2 on 2024-10-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='task',
            name='fineshed',
            field=models.BooleanField(default=False),
        ),
    ]
