# Generated by Django 5.1.2 on 2024-10-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_finished_at_task_fineshed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fineshed',
            new_name='finished',
        ),
    ]
