# Generated by Django 5.1.2 on 2024-10-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_fineshed_task_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finished',
            new_name='completed',
        ),
    ]
